//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AiGallery.Resources {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AiGallery.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Welcome to AiGallery.
        /// </summary>
        public static string ContactH1 {
            get {
                return ResourceManager.GetString("ContactH1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Feel free to reach out to us for any reason.
        /// </summary>
        public static string ContactP1 {
            get {
                return ResourceManager.GetString("ContactP1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a we welcome your questions or valuable suggestions and information.
        /// </summary>
        public static string ContactP2 {
            get {
                return ResourceManager.GetString("ContactP2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Contacts.
        /// </summary>
        public static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Data sent successfully.
        ///The images you have uploaded will be verified and, if they comply with the site&apos;s criteria, will be published on the home page..
        /// </summary>
        public static string DataSentSuccessfully {
            get {
                return ResourceManager.GetString("DataSentSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Message.
        /// </summary>
        public static string EmailBody {
            get {
                return ResourceManager.GetString("EmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Message sent!
        ///We will read your message as soon as possible.
        /// </summary>
        public static string EmailSentSuccessfully {
            get {
                return ResourceManager.GetString("EmailSentSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Images to upload.
        /// </summary>
        public static string ImagesToUpload {
            get {
                return ResourceManager.GetString("ImagesToUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Welcome to AiGallery.
        /// </summary>
        public static string LoadImagesH1 {
            get {
                return ResourceManager.GetString("LoadImagesH1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a A space where every image is crafted through the creativity of artificial intelligence.
        /// </summary>
        public static string LoadImagesP1 {
            get {
                return ResourceManager.GetString("LoadImagesP1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a feel free to submit one or more of your images; we would be delighted to receive them.
        /// </summary>
        public static string LoadImagesP2 {
            get {
                return ResourceManager.GetString("LoadImagesP2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a if they align with the site&apos;s vision, we will publish them as soon as possible!.
        /// </summary>
        public static string LoadImagesP3 {
            get {
                return ResourceManager.GetString("LoadImagesP3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Load your images.
        /// </summary>
        public static string LoadYourImages {
            get {
                return ResourceManager.GetString("LoadYourImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a AiGallery - Artistic gallery of images created by artificial intelligence.
        /// </summary>
        public static string MainTitle {
            get {
                return ResourceManager.GetString("MainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a must not exceed 100 characters.
        /// </summary>
        public static string MustNotExceed100Characters {
            get {
                return ResourceManager.GetString("MustNotExceed100Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a must not exceed 30 characters.
        /// </summary>
        public static string MustNotExceed30Characters {
            get {
                return ResourceManager.GetString("MustNotExceed30Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a must not exceed 500 characters.
        /// </summary>
        public static string MustNotExceed500Characters {
            get {
                return ResourceManager.GetString("MustNotExceed500Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Note.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Please enter your {0}.
        /// </summary>
        public static string PleaseEnterYour_0_ {
            get {
                return ResourceManager.GetString("PleaseEnterYour{0}", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Please provide a valid {0}.
        /// </summary>
        public static string PleaseProvideAvalid_0_ {
            get {
                return ResourceManager.GetString("PleaseProvideAvalid{0}", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Send.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Upload at least one image.
        /// </summary>
        public static string UploadAtLeastOneImage {
            get {
                return ResourceManager.GetString("UploadAtLeastOneImage", resourceCulture);
            }
        }
    }
}
